version: 2
pull_requests:
  validate:
    # Заголовок PR
    - title:
        must_include:
          regex: '^(feat|fix|docs|chore|test|refactor|ci|build): \[(BST|AVL|RBT)\] .+'
        message: "PR title must follow: 'type: [Tree] Description' (e.g., 'feat: [AVL] Add rotation')"
        min_length: 15
        max_length: 72

    # Тело PR
  - body:
      required: true
      message: "PR must have a description."

    # Лейблы
    - labels:
        required: ["BST", "AVL", "RBT", "bug", "documentation", "dependencies"]
        message: "Add at least one label (e.g., BST, documentation)"

    # Коммиты
    - commits:
        min: 1
        message:
          regex: '^(feat|fix|docs|chore|test|refactor|ci|build)(\(.*\))?: .+'
          message: "Commit messages must follow Conventional Commits"

    # Файлы
    - files:
        min: 1
        allow:
          - "**.kt"
          - "**.md"
        block:
          - "**.txt"

    # Ревью
    - reviews:
        min: 1
        from:
          - "NikolaiKl"
          - "lev666"
          - "ivanovm-main"

  block:
    - conflicts: true
    - wip: true
